CREATE TABLE IF NOT EXISTS courses
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    course_id  INT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    birthday   TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(id)
);

CREATE TABLE IF NOT EXISTS users
(
    id        INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(50) CHARACTER SET utf8mb3 NOT NULL,
    email     VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    token     VARCHAR(255) NULL
);
